import {
  TYPE_GAMER,
  TYPE_NOTEBOOK,
  STORAGE_256GB,
  STORAGE_512GB,
  STORAGE_1TB,
  RAM_8GB,
  RAM_16GB,
  RAM_32GB,
  RAM_64GB,
  CHIP_INTEL_I5,
  CHIP_INTEL_I7,
  CHIP_INTEL_I9,
  CHIP_RYZEN_5,
  CHIP_RYZEN_7,
  CHIP_RYZEN_9,
  CHIP_SNAPDRAGON,
  BRAND_DELL,
  BRAND_HP,
  BRAND_ASUS,
  BRAND_LENOVO,
  BRAND_ACER,
  BRAND_SAMSUNG,
  BRAND_MSI,
  SCREEN_13,
  SCREEN_14,
  SCREEN_15,
  SCREEN_16,
  SCREEN_17,
} from '../constantes/notebook'
export const notebooksProductos = [
  {
    id: 'Acer-Aspire-3',
    name: 'Acer Aspire 3',
    type: TYPE_NOTEBOOK,
    chip: CHIP_INTEL_I5,
    screen: SCREEN_13,
    brand: BRAND_ACER,
    storage: STORAGE_1TB,
    ram: RAM_16GB,
    category: 'notebook',
    brand: BRAND_ACER,
    desc: ' La Acer Aspire 3 de 15,6” es una notebook práctica, veloz y perfecta para el día a día. Su pantalla táctil Full HD brinda una experiencia visual cómoda y fluida, ideal para estudiar, trabajar o disfrutar tus series favoritas. Con diseño liviano, teclado numérico y gran capacidad de almacenamiento, es una excelente compañera para cualquier rutina.​​​​​',
    descSpecs: [
      {
        title: 'Tamaño',
        desc: 'Tamaño de pantalla: 27 pulgadas (68,58 cm) en diagonal',
      },
      {
        title: 'extras',
        desc: 'Integrated FHD 1080p Webcam, Dual array microphone, Dell Pro Wireless White Keyboard + Wireless White Mouse',
      },
      {
        title: 'sistema',
        desc: 'Windows 11 Home x64 bits, preinstalado.',
      },
    ],
    price: 123345,
    image: ['/images/macbook.png'],
  },
  {
    id: 'Acer-Aspire-3',
    name: 'Acer Aspire 3',
    type: TYPE_NOTEBOOK,
    chip: CHIP_INTEL_I5,
    screen: SCREEN_13,
    brand: BRAND_ACER,
    storage: STORAGE_1TB,
    ram: RAM_16GB,
    category: 'notebook',
    desc: 'La Acer Aspire 3 de 15,6” es una notebook práctica, veloz y perfecta para el día a día.',
    descSpecs: [
      {
        title: 'Tamaño',
        desc: 'Tamaño de pantalla: 15,6 pulgadas en diagonal',
      },
      {
        title: 'extras',
        desc: 'Webcam HD, teclado retroiluminado, Wi-Fi 6',
      },
      {
        title: 'sistema',
        desc: 'Windows 11 Home x64 bits, preinstalado.',
      },
    ],
    price: 123345,
    image: ['/images/macbook.png'],
  },
  {
    id: 'Dell-Inspiron-16',
    name: 'Dell Inspiron 16',
    type: TYPE_NOTEBOOK,
    chip: CHIP_RYZEN_7,
    screen: SCREEN_16,
    brand: BRAND_DELL,
    storage: STORAGE_512GB,
    ram: RAM_8GB,
    category: 'notebook',
    desc: 'La Dell Inspiron 16 ofrece un rendimiento excelente con su potente procesador Ryzen 7 y diseño moderno.',
    descSpecs: [
      {
        title: 'Tamaño',
        desc: 'Tamaño de pantalla: 16 pulgadas Full HD',
      },
      {
        title: 'extras',
        desc: 'Altavoces estéreo, teclado numérico, batería de larga duración',
      },
      {
        title: 'sistema',
        desc: 'Windows 11 Home preinstalado.',
      },
    ],
    price: 142900,
    image: ['/images/macbook.png'],
  },
  {
    id: 'HP-Pavilion-Gamer',
    name: 'HP Pavilion Gamer',
    type: TYPE_GAMER,
    chip: CHIP_INTEL_I7,
    screen: SCREEN_15,
    brand: BRAND_HP,
    storage: STORAGE_1TB,
    ram: RAM_32GB,
    category: 'notebook',
    desc: 'Diseñada para juegos y tareas exigentes, la HP Pavilion combina potencia y estilo gamer.',
    descSpecs: [
      {
        title: 'Tamaño',
        desc: 'Pantalla de 15,6 pulgadas antirreflejo',
      },
      {
        title: 'extras',
        desc: 'Teclado RGB, sistema de refrigeración avanzada, tarjeta gráfica dedicada',
      },
      {
        title: 'sistema',
        desc: 'Windows 11 Home.',
      },
    ],
    price: 189900,
    image: ['/images/macbook.png'],
  },
  {
    id: 'Lenovo-IdeaPad-14',
    name: 'Lenovo IdeaPad 14',
    type: TYPE_NOTEBOOK,
    chip: CHIP_RYZEN_5,
    screen: SCREEN_14,
    brand: BRAND_LENOVO,
    storage: STORAGE_256GB,
    ram: RAM_8GB,
    category: 'notebook',
    desc: 'Liviana, portátil y eficiente: perfecta para estudiantes y profesionales móviles.',
    descSpecs: [
      {
        title: 'Tamaño',
        desc: 'Pantalla de 14 pulgadas con resolución HD+',
      },
      {
        title: 'extras',
        desc: 'Cámara web con obturador, carga rápida, Dolby Audio',
      },
      {
        title: 'sistema',
        desc: 'Windows 11 Home',
      },
    ],
    price: 99900,
    image: ['/images/macbook.png'],
  },
  {
    id: 'ASUS-ROG-Strix',
    name: 'ASUS ROG Strix',
    type: TYPE_GAMER,
    chip: CHIP_INTEL_I9,
    screen: SCREEN_17,
    brand: BRAND_ASUS,
    storage: STORAGE_1TB,
    ram: RAM_64GB,
    category: 'notebook',
    desc: 'Máxima potencia para gaming competitivo y creación de contenido exigente.',
    descSpecs: [
      {
        title: 'Tamaño',
        desc: 'Pantalla de 17,3 pulgadas con tasa de refresco 144Hz',
      },
      {
        title: 'extras',
        desc: 'Teclado RGB Aura Sync, sistema de enfriamiento ROG, GPU RTX',
      },
      {
        title: 'sistema',
        desc: 'Windows 11 Pro',
      },
    ],
    price: 349990,
    image: ['/images/macbook.png'],
  },
  {
    id: 'Samsung-Galaxy-Book',
    name: 'Samsung Galaxy Book',
    type: TYPE_NOTEBOOK,
    chip: CHIP_SNAPDRAGON,
    screen: SCREEN_13,
    brand: BRAND_SAMSUNG,
    storage: STORAGE_512GB,
    ram: RAM_16GB,
    category: 'notebook',
    desc: 'Ultraliviana y silenciosa, ideal para productividad con gran autonomía y conectividad.',
    descSpecs: [
      {
        title: 'Tamaño',
        desc: 'Pantalla AMOLED de 13,3 pulgadas',
      },
      {
        title: 'extras',
        desc: 'Samsung DeX, sensor de huellas, modo ahorro inteligente',
      },
      {
        title: 'sistema',
        desc: 'Windows 11 ARM Edition',
      },
    ],
    price: 158700,
    image: ['/images/macbook.png'],
  },
]

export default notebooksProductos
