export const TYPE_WATCH_SE = 'WATCH_SE'
export const TYPE_WATCH_SERIE_10 = 'WATCH_SERIE_10'
export const TYPE_WATCH_ULTRA = 'ULTRA'
export const COLOR_GRIS = '#9b9b9b'
export const COLOR_AMARILLO = '#FFFF00'
export const COLOR_NEGRO = '#000000'
export const COLOR_ROSA = '#ffcocb'
export const COLOR_PLATA = '#COCOCO'
