import { Geist, Geist_Mono, Inter } from 'next/font/google'
import './globals.css'
import SiteChrome from './components/SiteChrome'
import Image from 'next/image'
const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Tengo Tecno',
  description: 'Generated by create next app',
  icons: { icon: '/images/TT.svg' },
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} antialiased relative w-full h-full `}>
        <SiteChrome>{children}</SiteChrome>
      </body>
    </html>
  )
}
