import { Geist, Geist_Mono, Inter } from 'next/font/google'
import './globals.css'
import Header from './(components)/header'
import ResponsiveFooter from './(components)/responsiveFooter'
const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang='en'>
        <body
          className={`${inter.variable} antialiased relative w-full h-full `}>
          <Header className='z-100' />
          {children}
          <ResponsiveFooter />
        </body>
      </html>
  )
}
